export default [
  "How did I know my girlfriend thought I was invading her privacy? She wrote about it in her diary.",
  "Why did the electric car feel discriminated against? Because the rules weren't current.",
  "I'm such a good navigator, a self-driving car once asked me for directions.",
  "Why do melons have weddings? They cantelope.",
  "What did the bison say to his son when he left the ranch? Bi-son.",
  "Watch what you say around the egg whites. They can't take a yolk.",
  "I'm so good at fixing things, my motto is, \"If it is broke, I'll still fix it.\"",
  "Where did the pumpkins have their meeting? In the gourdroom.",
  "What's the best way to save your dad jokes? In a dadda-base.",
  "I got a new pen that can write under water. It can write other words too.",
  "Did you hear about the king who went to the dentist? He needed a new crown.",
  "I used to play piano by ear, but now I use my hands.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "I don't trust stairs because they're always up to something.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "How do you organize a space party? You planet.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why couldn't the bicycle stand up by itself? It was two-tired.",
  "What do you call fake spaghetti? An impasta.",
  "Want to hear a joke about construction? I'm still working on it.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "I would avoid the sushi if I was you. It’s a little fishy.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "My wife told me I should do lunges to stay in shape. That would be a big step forward.",
  "Why do cows wear bells? Because their horns don't work.",
  "I made a pencil with two erasers. It was pointless.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "I'm reading a book on the history of glue. I just can't seem to put it down.",
  "What do you call a belt made of watches? A waist of time.",
  "I used to hate facial hair...but then it grew on me.",
  "Why couldn't the leopard play hide and seek? Because he was always spotted.",
  "I decided to sell my vacuum cleaner—it was just gathering dust.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "I know a lot of jokes about retired people… but none of them work.",
  "What do you call a can opener that doesn't work? A can't opener.",
  "Why did the math book look sad? Because it had too many problems.",
  "How does a penguin build its house? Igloos it together.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "I used to play piano by ear, but now I use my hands.",
  "Did you hear the rumor about butter? Well, I'm not going to spread it!",
  "How do you organize a space party? You planet.",
  "Why couldn't the bicycle stand up by itself? It was two-tired.",
  "I don't trust stairs. They're always up to something.",
  "Why did the orange stop rolling? It ran out of juice.",
  "What did the big flower say to the little flower? Hi, bud!",
  "I'm terrified of elevators, so I'm going to start taking steps to avoid them.",
  "Why did the coffee file a police report? It got mugged.",
  "How do you find Will Smith in the snow? You look for fresh prints.",
  "Why don’t oysters donate to charity? Because they’re shellfish.",
  "I'm so good at sleeping, I can do it with my eyes closed.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "What’s orange and sounds like a parrot? A carrot.",
  "Why did the cookie go to the hospital? Because it felt crummy.",
  "How do you make holy water? You boil the hell out of it.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why don’t crabs give to charity? Because they’re shellfish.",
  "What do you call fake spaghetti? An impasta.",
  "How does a penguin build its house? Igloos it together.",
  "I ordered a chicken and an egg online. I’ll let you know which comes first.",
  "What’s brown and sticky? A stick.",
  "I used to hate facial hair... but then it grew on me.",
  "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
  "Did you hear about the guy who invented Lifesavers? He made a mint.",
  "Why did the tomato blush? Because it saw the salad dressing.",
  "Why did the man fall into the well? Because he couldn’t see that well.",
  "Want to hear a construction joke? Oh... never mind, I’m still working on that one.",
  "I used to be addicted to soap, but I’m clean now.",
  "I couldn’t figure out why the baseball kept getting bigger. Then it hit me.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What’s the best way to watch a fly fishing tournament? Live stream.",
  "Why don't skeletons ever go trick or treating? Because they have no body to go with.",
  "I told my computer I needed a break, and now it won’t stop sending me KitKat ads.",
  "Why are elevator jokes so good? They work on many levels.",
  "What do you call a nervous javelin thrower? Shakespeare.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "I only know 25 letters of the alphabet. I don’t know y.",
  "How do you organize a space party? You planet.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "I told my wife she should embrace her mistakes... She hugged me.",
  "How do cows stay up to date? They read the moos-paper.",
  "I’m reading a book on anti-gravity. It’s impossible to put down.",
  "What did one wall say to the other? I’ll meet you at the corner.",
  "Did you hear about the kidnapping at school? It’s fine, he woke up.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "Why do bees have sticky hair? Because they use honeycombs.",
  "Why did the cookie go to the hospital? Because he felt crummy.",
  "Why did the math book look sad? Because it had too many problems.",
  "Why did the man get hit by a bike every day? He was stuck in a vicious cycle.",
  "What did the buffalo say to his son when he left? Bison.",
  "I made a pencil with two erasers. It was pointless.",
  "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
  "How do you find Will Smith in the snow? You look for fresh prints.",
  "What’s orange and sounds like a parrot? A carrot.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why was the math lecture so long? The professor kept going off on a tangent.",
  "I’m afraid for the calendar. Its days are numbered.",
  "What do you call fake spaghetti? An impasta.",
  "I used to play piano by ear, but now I use my hands.",
  "Did you hear about the guy who invented Lifesavers? He made a mint.",
  "I’m so good at sleeping, I can do it with my eyes closed.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Want to hear a construction joke? Oh… never mind, I’m still working on it.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "Why didn’t the vampire attack Taylor Swift? Because she had bad blood.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "I ordered a chicken and an egg online. I’ll let you know.",
  "What’s brown and sticky? A stick.",
  "How does a penguin build its house? Igloos it together.",
  "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.",
  "I used to hate facial hair… but then it grew on me.",
  "What do you call a hot dog on wheels? Fast food.",
  "Why do melons have weddings? Because they cantaloupe.",
  "I made a pencil with two erasers. It was pointless.",
  "I used to be addicted to the hokey pokey… but then I turned myself around.",
  "Why can’t you hear a psychiatrist using the bathroom? Because the 'P' is silent.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "I bought some shoes from a drug dealer. I don’t know what he laced them with, but I was tripping all day.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "How do you organize a space party? You planet.",
  "Did you hear about the kidnapping at school? It’s fine, he woke up.",
  "Why did the coffee file a police report? It got mugged.",
  "How does Moses make his coffee? Hebrews it.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "Why don’t crabs give to charity? Because they’re shellfish.",
  "I’m reading a book about anti-gravity. It’s impossible to put down.",
  "I used to have a job as a professional cricket impersonator, but I was let go.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call an elephant that doesn’t matter? An irrelephant.",
  "I gave all my dead batteries away today… free of charge.",
  "Did you hear the rumor about butter? Well, I’m not going to spread it.",
  "Why did the man get hit by a bike every day? He was stuck in a vicious cycle.",
  "I told my friend she drew her mole wrong… now she’s *fumin’.*","What do you call someone with no body and no nose? Nobody knows.",
  "I told my son I was named after Thomas Jefferson… He said, 'But Dad, your name is Brian.' I said, 'I know, but I was named *after* him.'",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "I used to play piano by ear, but now I use my hands.",
  "Why did the bicycle fall over? Because it was two tired.",
  "My wife told me to stop impersonating a flamingo. I had to put my foot down.",
  "I made a playlist for hiking. It has music from Peanuts, The Cranberries, and Eminem… I call it 'Trail Mix.'",
  "If you see a crime at an Apple store, does that make you an iWitness?",
  "I used to be a baker, but I couldn’t make enough dough.",
  "How many apples grow on a tree? All of them.",
  "I told my wife she was average. She said, 'That’s just mean!'",
  "I tried to catch some fog earlier… I mist.",
  "What do you get from a pampered cow? Spoiled milk.",
  "I cut my finger chopping cheese… but I think that I may have grater problems.",
  "My friend wants to become an archaeologist, but I’m trying to put him off — his life will be in ruins.",
  "I stayed up all night wondering where the sun went. Then it dawned on me.",
  "I accidentally swallowed some food coloring. The doctor says I’m OK but I feel like I’ve dyed a little inside.",
  "Two guys walked into a bar. The third guy ducked.",
  "What do you call cheese that isn’t yours? Nacho cheese.",
  "I’m on a whiskey diet. I’ve lost three days already.", "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "I used to be addicted to the hokey pokey… but then I turned myself around.",
  "Why can’t you hear a pterodactyl using the bathroom? Because the 'P' is silent.",
  "I asked my dog what's two minus two. He said nothing.",
  "What did the janitor say when he jumped out of the closet? 'Supplies!'",
  "I made a pencil with two erasers. It was pointless.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I used to play piano by ear, but now I use my hands.",
  "I stayed up all night wondering where the sun went. Then it dawned on me.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "I got a job at a bakery because I kneaded dough.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "How do you make holy water? You boil the hell out of it.",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "What do you call fake spaghetti? An impasta.",
  "Why did the tomato blush? Because it saw the salad dressing.",
  "I don’t trust stairs. They’re always up to something.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "Why did the math book look sad? It had too many problems.",
  "Did you hear about the guy who invented Lifesavers? He made a mint.",
  "I ordered a chicken and an egg from Amazon. I’ll let you know.",
  "What did the grape do when he got stepped on? Nothing but let out a little wine.",
  "How does a penguin build its house? Igloos it together.",
  "Why can’t your nose be 12 inches long? Because then it would be a foot.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "What’s orange and sounds like a parrot? A carrot.",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "What’s brown and sticky? A stick.",
  "Did you hear about the kidnapping at school? It’s fine, he woke up.",
  "Why don’t some couples go to the gym? Because some relationships don’t work out.",
  "How do cows stay up to date? They read the moos-paper.",
  "What do you call a belt made out of watches? A waist of time.",
  "Why did the coffee file a police report? It got mugged.",
  "I told my computer I needed a break, and now it won’t stop sending me Kit-Kats.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "Why are elevator jokes so good? They work on many levels.",
  "I’m afraid for the calendar. Its days are numbered.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "How do you organize a space party? You planet.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "What do you call a pile of cats? A meowtain.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "I used to hate facial hair... but then it grew on me.",
  "I’m on a seafood diet. I see food and I eat it.",
  "Why was the math book sad? It had too many problems.",
  "Want to hear something that’ll make you smile? Your face muscles.",
  "Why did the bicycle fall over? It was two-tired.",
  "I told my wife she should embrace her mistakes. She hugged me.",
  "I only know 25 letters of the alphabet. I don’t know y.",
  "How do you make holy water? You boil the hell out of it.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "How do you find Will Smith in the snow? You look for fresh prints.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What lights up a soccer stadium? A soccer match.",
  "Why did the cookie go to the hospital? It felt crummy.",
  "How do you make a tissue dance? Put a little boogie in it.",
  "Why can’t you hear a pterodactyl go to the bathroom? Because the ‘P’ is silent.",
  "I asked the dog what’s two minus two. He said nothing.",
  "Why don’t Endermen ever get invited to parties? They always teleport away when things get heated.",
  "What’s a creeper’s favorite type of music? Boom-box.",
  "I tried building a house in Minecraft with glass walls. People say I shouldn’t throw stones.",
  "Why did Steve get kicked out of the restaurant? He was mining his own business… too loudly.",
  "Why don’t Minecraft players ever get lost? They always have their coordinates straight.",
  "How do you tame a Minecraft wolf? With a bone to pick.",
  "What did the Minecraft pig say to the carrot? ‘I’m rootin’ for ya!’",
  "Why did the zombie go to therapy? He had trouble *fleshing* out his feelings.",
  "I named my Minecraft horse ‘Mayonnaise’… because when I open the stable, Mayo neighs.",
  "How does Steve keep his pants up? With a belt enchantment!",
  "Why did the creeper break up with the skeleton? There was no *spark* anymore.",
  "I asked the Minecraft bee for dating advice. Now I’m stuck in a *buzzing* relationship.",
  "Why did Steve make a shovel out of gold? Because he *digs* flashy stuff.",
  "How do you make a crafting table laugh? You give it a *wooden pun-chline*.",
  "What’s a Minecraft ghast’s favorite romantic movie? ‘Ghost’—he cries every time.",
  "Why don’t villagers ever tell secrets? Because they only know how to *hmmm* and nod.",
  "I built my bed too close to the wall. Now I sleep on the *edge*… literally.",
  "Why did the block of dirt start a podcast? It wanted to talk about *growing* pains.",
  "What’s the most emotional block in Minecraft? Obsidian—it bottles things up under pressure.",
  "Why did the parrot leave the jungle? Too much *cheep* talk.",
  "What did one wall say to the other wall? I'll meet you at the corner.",
  "I used to play piano by ear, but now I use my hands.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I ordered a chicken and an egg online… I’ll let you know which comes first.",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "How do you make holy water? You boil the hell out of it.",
  "I’m on a seafood diet. I see food and I eat it.",
  "I used to hate facial hair… but then it grew on me.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "What do you call cheese that isn't yours? Nacho cheese.",
];
